@startuml
skinparam defaultTextAlignment left
caption Behavior of thing Button1
[*] --> TestButton
state TestButton{
state Waiting{
	Waiting : but?press / \naction print "PRESS\\n"\n
	Waiting : but?release / \naction print "RELEASE\\n"\n
}
[*] --> Waiting
	TestButton : entry / print "READY!\\n"\n
}
@enduml
