@startuml
[*] --> TestButton
state TestButton{
state Waiting{
	Waiting : internal press?but\ndo print ''PRESS\\n''\n
	Waiting : internal release?but\ndo print ''RELEASE\\n''\n
}
[*] --> Waiting
	TestButton : entry / print "READY!\n"

}
@enduml
