@startuml
caption Things used in configuration Button3App
class Button <<(T,#F94918)PSM>> {
..Properties..
-PIN : UInt8 = 8
..Port clock..
>>ms25_tic
..Port evt..
<<press
<<release
..Functions..
-is_pressed() : Boolean
}
class ButtonMsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-press()
-release()
}
class TimerMsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-timer_start(...)
-timer_cancel(...)
-timer_timeout(...)
-ms25_tic()
-ms500_tic()
}
class TestSoftButtonLongPress <<(T,#5BBF09)PIM>> {
..Port led..
<<led_ON
<<led_OFF
..Port softbut..
>>long_press
}
class SoftButtonMsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-click()
-double_click()
-long_press()
}
class LEDMsgs <<(T,#5BBF09)PIM>> {
..Messages..
-led_ON()
-led_OFF()
}
class LED <<(T,#F94918)PSM>> {
..Properties..
-PIN : UInt8 = 11
..Port ctrl..
>>led_ON
>>led_OFF
..Functions..
-setDigitalOutput(...) : void
-digitalWrite(...) : void
}
class SoftButton <<(T,#5BBF09)PIM>> {
..Properties..
-long_delay : UInt16 = 1000
-double_delay : UInt16 = 250
..Port Button..
>>press
>>release
..Port Timer..
>>timer_timeout
<<timer_start
<<timer_cancel
..Port SoftButton..
<<click
<<double_click
<<long_press
}
class TestSoftButtonDoubleClick <<(T,#5BBF09)PIM>> {
..Port led..
<<led_ON
<<led_OFF
..Port softbut..
>>double_click
>>click
}
ButtonMsgs <|-- Button
TimerMsgs <|-- Button
SoftButtonMsgs <|-- TestSoftButtonLongPress
LEDMsgs <|-- TestSoftButtonLongPress
LEDMsgs <|-- LED
ButtonMsgs <|-- SoftButton
SoftButtonMsgs <|-- SoftButton
TimerMsgs <|-- SoftButton
SoftButtonMsgs <|-- TestSoftButtonDoubleClick
LEDMsgs <|-- TestSoftButtonDoubleClick
@enduml