@startuml
caption Instances and Connectors in configuration Button3App
component button<<PSM>>
component app2<<PIM>>
component l1<<PSM>>
component sbut<<PIM>>
component app1<<PIM>>
component l2<<PSM>>
boundary Timer
app1 -(0- sbut : softbut => SoftButton
sbut -(0- button : Button => evt
app2 -(0- l2 : led => ctrl
app1 -(0- l1 : led => ctrl
app2 -(0- sbut : softbut => SoftButton
button .. Timer : clock
sbut .. Timer : Timer
@enduml