@startuml
skinparam defaultTextAlignment left
caption Behavior of thing TestSoftButtonDoubleClick
[*] --> Region1
state Region1{
state OFF{
	OFF : entry / led!led_OFF()\n

OFF --> ON : softbut?double_click
}
state ON{
	ON : entry / led!led_ON()\n

ON --> OFF : softbut?double_click
}
[*] --> OFF
	Region1 : softbut?click / \naction print "CLICK\\n"\n
}
@enduml
