@startuml
node "Blink3App"{
[blink1]
[blink2]
ctrl_led13 - [led13]
[blink2] -> ctrl_led13 : led
[Blink3App_blink1] ..> org.sintef.thingml.impl.ProtocolImpl@7a36aefa (name: Timer)
[Blink3App_blink2] ..> org.sintef.thingml.impl.ProtocolImpl@7a36aefa (name: Timer)
}
@enduml