@startuml
[*] --> LED
state LED{
state READY{
	READY : internal led_ON?ctrl\ndo digitalWrite(PIN1)\n
	READY : internal led_OFF?ctrl\ndo digitalWrite(PIN0)\n
}
[*] --> READY
	LED : entry / setDigitalOutput(PIN)

}
@enduml
