@startuml
skinparam defaultTextAlignment left
caption Behavior of thing Blink2
[*] --> Blink
state Blink{
state OFF{
	OFF : entry / do \nled!led_OFF()\ntimer!timer_start(...)\nend\n

OFF --> ON : e:timer?timer_timeout
}
state ON{
	ON : entry / do \nled!led_ON()\ntimer!timer_start(...)\nend\n

ON --> OFF : e:timer?timer_timeout
}
[*] --> OFF
}
@enduml
