@startuml
node "Button3App"{
[app]
SoftButton_sbut - [sbut]
ctrl_l2 - [l2]
evt_button - [button]
ctrl_l1 - [l1]
[app] -> SoftButton_sbut : softbut
[sbut] -> evt_button : Button
[app] -> ctrl_l1 : led1
[app] -> ctrl_l2 : led2
[Button3App_button] ..> org.sintef.thingml.impl.ProtocolImpl@58a90037 (name: Timer)
[Button3App_sbut] ..> org.sintef.thingml.impl.ProtocolImpl@58a90037 (name: Timer)
}
@enduml