@startuml
[*] --> Button
state Button{
state RELEASED{
RELEASED --> PRESSED : 25ms_tic?clock\nif is_pressed()\ndo evt!press()\n
}
state PRESSED{
PRESSED --> RELEASED : 25ms_tic?clock\nif  not(is_pressed())\ndo evt!release()\n
}
[*] --> RELEASED
}
@enduml
