@startuml
[*] --> Region1
state Region1{
state OFF{
	OFF : entry / led1!led_OFF()

OFF --> ON : double_click?softbut
}
state ON{
	ON : entry / led1!led_ON()

ON --> OFF : double_click?softbut
}
[*] --> OFF
	Region1 : internal click?softbut\ndo print ''CLICK\\n''\n
--
[*] --> OFF
state OFF{
	OFF : entry / led2!led_OFF()

OFF --> ON : long_press?softbut
}
state ON{
	ON : entry / led2!led_ON()

ON --> OFF : long_press?softbut
}
}
@enduml
