@startuml
node "Button2App"{
ctrl_l2 - [l2]
[app]
evt_button - [button]
ctrl_l1 - [l1]
[app] -> evt_button : but
[app] -> ctrl_l1 : led1
[app] -> ctrl_l2 : led2
[Button2App_button] ..> org.sintef.thingml.impl.ProtocolImpl@768b970c (name: Timer)
[Button2App_app] ..> org.sintef.thingml.impl.ProtocolImpl@768b970c (name: Timer)
}
@enduml