@startuml
[*] --> TestButton
state TestButton{
state Waiting{
	Waiting : entry / do\nled1!led_OFF()\nled2!led_OFF()\nend
	Waiting : internal press?but\ndo led1!led_ON()\ntimer!timer_start(01000)\n
	Waiting : internal release?but\ndo led2!led_ON()\ntimer!timer_start(11000)\n
	Waiting : internal timer_timeout?timer\ndo if(e.id == 0) {\nled1!led_OFF()\n\n} else {\nif(e.id == 1) {\nled2!led_OFF()\n\n}\n\n}\n
}
[*] --> Waiting
}
@enduml
