@startuml
[*] --> Blink
state Blink{
state OFF{
	OFF : entry / do\nled!led_OFF()\ntimer!timer_start(01200)\nend
OFF --> ON : timer_timeout?timer
}
state ON{
	ON : entry / do\nled!led_ON()\ntimer!timer_start(050)\nend
ON --> OFF : timer_timeout?timer
}
[*] --> OFF
}
@enduml
