@startuml
skinparam defaultTextAlignment left
caption Behavior of thing TestButton
[*] --> TestButton
state TestButton{
state Waiting{
	Waiting : entry / do \nled1!led_OFF()\nled2!led_OFF()\nend\n
	Waiting : but?press / \naction do \nled1!led_ON()\ntimer!timer_start(...)\nend\n
	Waiting : but?release / \naction do \nled2!led_ON()\ntimer!timer_start(...)\nend\n
	Waiting : e:timer?timer_timeout / \naction if(timer_timeout.id == 0) do\nled1!led_OFF()\nend else do\nif(timer_timeout.id == 1) do\nled2!led_OFF()\nend\n\n
}
[*] --> Waiting
}
@enduml
