@startuml
caption Things used in configuration Blink2App
class Blink2 <<(T,#5BBF09)PIM>> {
..Port timer..
>>timer_timeout
<<timer_start
<<timer_cancel
..Port led..
<<led_ON
<<led_OFF
}
class TimerMsgs <<(F,#BC74ED)Fragment>> {
..Messages..
-timer_start(...)
-timer_cancel(...)
-timer_timeout(...)
-ms25_tic()
-ms500_tic()
}
class LEDMsgs <<(T,#5BBF09)PIM>> {
..Messages..
-led_ON()
-led_OFF()
}
class LED <<(T,#F94918)PSM>> {
..Properties..
-PIN : UInt8 = 11
..Port ctrl..
>>led_ON
>>led_OFF
..Functions..
-setDigitalOutput(...) : void
-digitalWrite(...) : void
}
TimerMsgs <|-- Blink2
LEDMsgs <|-- Blink2
LEDMsgs <|-- LED
@enduml